tasks:
  - name: Install dependencies
    init: pip install pip install --upgrade pip -r requirements.txt

vscode:
  extensions:
    - ms-python.python

    - ms-toolsai.jupyter


    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
####pip install -r requirements.txt